### PR TITLE
sonarr: bump to 2.0.0.4949

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by thoradia — CHANGES_REQUESTED** [review]
Thanks!
Please also update PKG_REV and changelog.txt, see eg https://github.com/thoradia/LibreELEC.tv/commit/16ba0692c6c11a760ea3199d4cc6e09ad18faab1

**Comment by thoradia** [comment]
To update Sonarr manually, go to System/Updates in the web UI.
To update Sonarr automatically, go to Settings/General/Advanced Settings/Updates in the web UI.

**Comment by ghost** [comment]
updated package.mk
and changelog.txt

**Comment by thoradia** [comment]
committed as 8c253d7

**Pull request closed without merging**
